### ISSUE TITLE
FormattedMessage导出失败

### ISSUE THREAD

**Issue by nineMusic** [jsxiaosi/react-xs-admin#1]
src\layout\components\AppMain\TabsPage\index.tsx，文件中import { FormattedMessage } from ‘@/locales’导入出错，locales/index.tsx中没有导出的FormattedMessage,需要修改为import { useLocale } from '@/locales';，并且在下面添加一句const { formatMessage: FormattedMessage } = useLocale();

**Comment by jsxiaosi** [comment]
已修复~！为了兼容eslint react-refresh/only-export-components规则，所以把FormattedMessage组件单独迁移到了components，目前把`import { FormattedMessage } from ‘@/locales’` 更改成 `import { FormattedMessage } from '@/components/FormattedMessage';`
